sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
    - master
notifications:
  email: false 

before_script:
  -
script:
  - npm install
  - npm run build
  - npm run deploy
after_success:
  - npm run build

