sudo: false
language: node_js
node_js:
  - "10"
notifications:
  email: false 

before_script:
  - npm install
script:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  - npm run build

if: branch = master
after_success:
  - npm run deploy
