sudo: false
language: node_js
node_js:
  - "10"
notifications:
  email: false 

before_script:
   - npm install
   - npm run build
script:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then ./ci/deploy.rb envdev.tld; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./ci/deploy.rb envprod.tld; fi
after_success:
  -
