sudo: false
language: node_js
node_js:
  - "10"
notifications:
  email: false 

before_script:
  - npm install
script:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  - npm run build
after_success:
  - if [ $TRAVIS_BRANCH == "master" ]; then npm run deploy
